import './globals.css'


export const metadata = {
  title: 'AIgility',
  description: 'Generated by Dami-Olus',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f5f6f8]'>{children}</body>
    </html>
  )
}
